### ISSUE TITLE
音效minecraft:railway.nclm.line1.trainnextcentrallibrary无声音

### ISSUE THREAD

**Issue by nclmredtea** [Leo204-LKY/NAHGN-Sound-Pack#2]
情景:在其他音效均播放正常的情况下，minecraft:railway.nclm.line1.trainnextcentrallibrary音效正常播放，但没有声音。
使用命令:/playsound minecraft:railway.nclm.line1.trainnextcentrallibrary player Minecraft_jiajia
错误信息:无

**Comment by Leo204-LKY** [comment]
已解决。
请下载v1.0.1版本。
