### ISSUE TITLE
大部分音效存在语速过快的问题；相比于深圳地铁，缺少部分提示音。

### ISSUE THREAD

**Issue by nclmredtea** [Leo204-LKY/NAHGN-Sound-Pack#3]
问题描述:大部分音效语速过快，同种语言单词间间隔太短，缺少部分提示音。
例:在minecraft:railway.nclm.line1.trainnextoldtowneast音效中的中文部分，两声"古城东"的间隔过小，容易让人误解，且在"右侧车门将会打开"后，应加上"请小心列车与站台之间的空隙",英文部分同理。

**Comment by Leo204-LKY** [comment]
+ 语速过快，间隔较小
  + 收到反馈。
  + 由于录制语音再转码流程较繁琐，暂时不会对目前的地铁语音做出调整。
+ 缺少提示音
  + 录音时本着简洁的原则，只保留必要的语句
  + 同样，暂时不会做出调整。

**Comment by Leo204-LKY** [comment]
## 你的建议正在处理  

预计本周内完成发布。

**Comment by Leo204-LKY** [comment]
#### 建议已采纳。
感谢你的反馈。你的建议已采纳。

**Comment by Leo204-LKY** [comment]
#### 补充说明  
广播系统短期内仍将采取简洁的播报原则。  
我参考了国内 _（包含香港、台湾，但未曾了解过澳门轻轨的广播内容[但由于澳门轻轨2023年前由港铁（澳门）承运，内容应与香港类似。]）_ 许多城市的广播内容，综合后决定在原内容的基础上添加`本次列车终点站。[站名]。`及英文`This train is bound for [Terminus Name].`；同时修改了原内容。详细请查看 Wiki 页面编辑记录。
