### ISSUE TITLE
音效泠鸢yousa-黑猫添加申请

### ISSUE THREAD

**Issue by nclmredtea** [Leo204-LKY/NAHGN-Sound-Pack#4]
命令定义：nclmredtea.music.yousa.blackcat
保存位置：NCLMREDTEA/music/yousa
字幕文字：正在播放泠鸢yousa-黑猫(或正在播放泠鸢-黑猫)
文件链接：https://pan.baidu.com/s/15xLN5Q4TbtDWlsB8gJzToA 提取码:1r9l

**Comment by nclmredtea** [comment]
修正(为了避免误解的提示)
保存位置应为
NCLMREDTEA/music/yousa/blackcat
yousa是最后一级文件夹,blackcat为音频文件

**Comment by Leo204-LKY** [comment]
### 你的音效申请未通过。
**原因：**文件超过 2.5MB 的限制。_（新的上传限制为512 KB/30s）_
请考虑使用 [Compress.com](https://www.compresss.com/cn/compress-ogg.html "点击将重定向至 Compress.com。) 进行**有损**压缩或其他方式压缩后重新申请。
