### ISSUE TITLE
音效nclmredtea.music.yousa.blackcat添加申请

### ISSUE THREAD

**Issue by nclmredtea** [Leo204-LKY/NAHGN-Sound-Pack#5]
命令定义：nclmredtea.music.yousa.blackcat
保存位置：NCLMREDTEA/music/yousa/blackcat
字幕文字：正在播放泠鸢yousa-黑猫(或正在播放泠鸢-黑猫)
文件链接：已通过其他方式发送

**Comment by Leo204-LKY** [comment]
### 你的申请已通过
将于下次更新时加入。

**Comment by Leo204-LKY** [comment]
### 音效已添加
音效已加入音效包。请等待下次常规更新。

**Comment by Leo204-LKY** [comment]
## 调整说明  
### 请注意，你的音效已设置为`随距离衰减`  
这意味着声音将随着玩家离开开始播放位置的距离逐渐减弱音量。  
如需修改此项设置，请在本 Issue 下方提出；如不需要修改，请点击`Close`按钮关闭本 Issue。

**Comment by Leo204-LKY** [comment]
## 调整说明  
### 请注意，你的音效已设置为`随距离衰减`  
这意味着声音将随着玩家离开开始播放位置的距离逐渐减弱音量。  
如需修改此项设置，请在本 Issue 下方提出；如不需要修改，请点击`Close`按钮关闭本 Issue。

**Comment by nclmredtea** [comment]
暂不修改
